source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'SnapKit'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'FDFullscreenPopGesture'
pod 'NVActivityIndicatorView'
pod 'Kingfisher'
pod 'AwesomeCache'